# Generated by Django 5.2.17 on 2026-09-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequest',
            name='status',
            field=models.CharField(choices=[('AWAITING_ID', 'Awaiting ID'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='AWAITING_ID', max_length=16),
        ),
    ]
