# Generated by Django 5.2.17 on 2026-10-01 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_owner_disclosures'),
        ('properties', '0007_propertyfee_property_fe_propert_09c2cf_idx'),
        ('scheduler', '0002_tour_status_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='time_is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourrequest',
            name='preferred_time',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='tourrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('time_end__isnull', True), ('time_start__isnull', True)), models.Q(('time_end__gt', models.F('time_start')), ('time_end__isnull', False), ('time_start__isnull', False)), _connector='OR'), name='tour_window_complete_and_ordered'),
        ),
    ]
