# Generated by Django 5.1.15 on 2026-08-17 23:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'invoice_sequences',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('issued_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('line_items', models.JSONField(default=list)),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('tax_basis_points', models.PositiveIntegerField(default=0)),
                ('tax_amount_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('pdf_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=8)),
                ('due_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.rentalapplication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer (ACH)'), ('ZELLE', 'Zelle'), ('CASHAPP', 'Cash App'), ('CHIME', 'Chime'), ('PAYPAL', 'PayPal'), ('CHECK', 'Check or money order'), ('OTHER', 'Something else')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('handle', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('extra_instructions', models.TextField(blank=True, default='')),
                ('irreversible', models.BooleanField(default=False)),
                ('clearing_time', models.CharField(blank=True, default='', max_length=60)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_type', models.CharField(blank=True, default='', max_length=40)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('routing_number', models.CharField(blank=True, default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_method_configs',
                'constraints': [models.CheckConstraint(condition=models.Q(('is_active', False), models.Q(('handle', ''), _negated=True), models.Q(('account_number', ''), _negated=True), _connector='OR'), name='active_method_has_details')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer (ACH)'), ('ZELLE', 'Zelle'), ('CASHAPP', 'Cash App'), ('CHIME', 'Chime'), ('PAYPAL', 'PayPal'), ('CHECK', 'Check or money order'), ('OTHER', 'Something else')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_VERIFICATION', 'Awaiting verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING_VERIFICATION', max_length=24)),
                ('reference_id', models.CharField(blank=True, default='', max_length=60)),
                ('proof_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice')),
                ('rental_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.rentalapplication')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='payment_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['VERIFIED', 'REJECTED']), _negated=True), models.Q(('verified_by__isnull', False), ('verified_at__isnull', False)), _connector='OR'), name='decided_payment_records_actor'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='rejected_payment_has_reason')],
            },
        ),
    ]
