# Generated by Django 5.2.17 on 2026-08-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ACH', 'ACH transfer'), ('WIRE', 'Wire transfer'), ('DIRECT_DEPOSIT', 'Direct deposit'), ('BANK_TRANSFER', 'Bank transfer'), ('CHECK', 'Check or money order'), ('ZELLE', 'Zelle'), ('VENMO', 'Venmo'), ('CASHAPP', 'Cash App'), ('CHIME', 'Chime'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay'), ('LITECOIN', 'Litecoin'), ('SOLANA', 'Solana'), ('OTHER', 'Something else')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='method',
            field=models.CharField(choices=[('ACH', 'ACH transfer'), ('WIRE', 'Wire transfer'), ('DIRECT_DEPOSIT', 'Direct deposit'), ('BANK_TRANSFER', 'Bank transfer'), ('CHECK', 'Check or money order'), ('ZELLE', 'Zelle'), ('VENMO', 'Venmo'), ('CASHAPP', 'Cash App'), ('CHIME', 'Chime'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay'), ('LITECOIN', 'Litecoin'), ('SOLANA', 'Solana'), ('OTHER', 'Something else')], max_length=20, unique=True),
        ),
    ]
