# Generated by Django 5.1.15 on 2026-08-17 23:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, default='')),
                ('template', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('send_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'outbound_emails',
                'ordering': ['send_after'],
                'indexes': [models.Index(fields=['status', 'send_after'], name='outbound_em_status_3e8834_idx')],
            },
        ),
    ]
