# Generated by Django 5.2.17 on 2026-08-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
