# Generated by Django 5.1.15 on 2026-08-17 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'amenity categories',
                'db_table': 'amenity_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('residential', 'Single-family'), ('townhouse', 'Townhome'), ('condo', 'Condo'), ('apartment', 'Apartment')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available now'), ('coming-soon', 'Coming soon'), ('application-pending', 'Application pending'), ('leased', 'Leased'), ('off-market', 'Off market')], db_index=True, default='available', max_length=24)),
                ('price_cents', models.BigIntegerField(db_index=True)),
                ('original_price_cents', models.BigIntegerField(blank=True, null=True)),
                ('price_label', models.CharField(blank=True, default='/mo', max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('half_bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('sqft', models.PositiveIntegerField(default=0)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('garage', models.PositiveSmallIntegerField(default=0)),
                ('stories', models.PositiveSmallIntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=100)),
                ('voucher_accepted', models.BooleanField(db_index=True, default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('pet_policy', models.TextField(blank=True, default='')),
                ('accessibility_features', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('homepage_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'favorite properties',
                'db_table': 'favorite_properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.amenitycategory')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'property amenities',
                'db_table': 'property_amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_key', models.SlugField()),
                ('label', models.CharField(max_length=120)),
                ('amount_cents', models.BigIntegerField()),
                ('cadence', models.CharField(choices=[('monthly', 'Monthly'), ('one-time', 'One time')], default='monthly', max_length=10)),
                ('condition', models.CharField(choices=[('required', 'Required'), ('conditional', 'Conditional')], default='required', max_length=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('applies_when', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='properties.property')),
            ],
            options={
                'db_table': 'property_fees',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['-is_primary', 'sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['state', 'city'], name='properties_state_67bfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'status'], name='properties_is_publ_b3095b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='properties_latitud_5ee5e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('leased_at__isnull', False), ('status', 'leased')), models.Q(('status', 'leased'), _negated=True), _connector='OR'), name='leased_property_has_leased_at'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gte', 0)), name='price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='favoriteproperty',
            constraint=models.UniqueConstraint(fields=('user', 'property'), name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='propertyamenity',
            constraint=models.UniqueConstraint(fields=('property', 'slug'), name='unique_amenity_per_property'),
        ),
        migrations.AddConstraint(
            model_name='propertyfee',
            constraint=models.UniqueConstraint(fields=('property', 'fee_key'), name='unique_fee_key_per_property'),
        ),
        migrations.AddConstraint(
            model_name='propertyfee',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='fee_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertyfee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('condition', 'conditional'), _negated=True), models.Q(('applies_when', ''), _negated=True), _connector='OR'), name='conditional_fee_states_when'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('property',), name='one_primary_image_per_property'),
        ),
    ]
