# Generated by Django 5.2.17 on 2026-08-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'home', 'verbose_name_plural': 'homes'},
        ),
    ]
