# Generated by Django 5.2.17 on 2026-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='appliances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='flooring',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='hvac',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='laundry',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='tour_3d_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='tour_video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
