# Generated by Django 5.2.17 on 2026-08-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_appliances_property_flooring_property_hvac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='search_text',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
    ]
