# Generated by Django 5.2.17 on 2026-08-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor_plans',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='office_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='raw_fees',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='schools',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
