# Generated by Django 5.2.17 on 2026-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_floor_plans_property_office_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allow_selfshow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='api_endpoint',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='cross_street',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(default='for-rent', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='tour_360_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
