# Generated by Django 5.2.17 on 2026-09-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_allow_selfshow_property_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='propertyfee',
            index=models.Index(fields=['property', 'cadence', 'condition'], name='property_fe_propert_09c2cf_idx'),
        ),
    ]
