# Generated by Django 5.1.15 on 2026-08-17 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_id', models.CharField(blank=True, default='', max_length=60)),
                ('role_title', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('motivation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=24)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('RENTER_GUIDE', 'Renter guide'), ('MARKET_UPDATE', 'Market update'), ('MARKET_ANALYSIS', 'Market analysis'), ('BUYERS_GUIDE', "Buyer's guide"), ('SELLERS_GUIDE', "Seller's guide"), ('INVESTMENT', 'Investment')], max_length=20)),
                ('featured_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('read_time_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
