# Generated by Django 5.2.17 on 2026-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='questionnaire',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
