# Generated by Django 5.1.15 on 2026-08-17 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file_url', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('RECEIPT', 'Receipt'), ('AGREEMENT', 'Agreement'), ('ID_DOCUMENT', 'Identity document'), ('PROOF_OF_FUNDS', 'Proof of funds'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('HVAC', 'Heating and cooling'), ('APPLIANCE', 'Appliance'), ('STRUCTURAL', 'Structural'), ('PEST', 'Pest'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=8)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='SUBMITTED', max_length=16)),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('preferred_access_time', models.CharField(blank=True, default='', max_length=120)),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='crm.client')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
            ],
            options={
                'db_table': 'maintenance_requests',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
