# Generated by Django 5.2.17 on 2026-08-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'rental application', 'verbose_name_plural': 'rental applications'},
        ),
    ]
