# Generated by Django 5.2.17 on 2026-08-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_rentalapplication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
