# Generated by Django 5.2.17 on 2026-08-23 11:23

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rentalapplication_draft_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='drivers_license_number',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='drivers_license_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='employer_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='mothers_maiden_name',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_residence_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_zip',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='ssn',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='supervisor_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
