# Generated by Django 5.2.17 on 2026-08-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rentalapplication_drivers_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('CONTACT_FORM', 'Contact form'), ('PROPERTY_INQUIRY', 'Property inquiry'), ('AGENT_INQUIRY', 'Agent inquiry'), ('REFERRAL', 'Referral'), ('GOOGLE', 'Google'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('DIRECT', 'Direct'), ('CALLBACK', 'Callback request')], default='CONTACT_FORM', max_length=24),
        ),
    ]
