# Generated by Django 5.2.17 on 2026-09-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_lead_email_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='landlord_address',
            field=models.CharField(blank=True, default='213 Bob Ln, Virginia Beach, VA 23454', max_length=300),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='landlord_company',
            field=models.CharField(blank=True, default='Skelton Realty Group', max_length=200),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='landlord_email',
            field=models.EmailField(blank=True, default='kenneth@skeltonrealtygroup.com', max_length=254),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='landlord_name',
            field=models.CharField(blank=True, default='Kenneth Hensley Jr', max_length=200),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='landlord_phone',
            field=models.CharField(blank=True, default='(800) 555-0198', max_length=50),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_emergency_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_occupants',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_signature_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_vehicles',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
