# Generated by Django 5.2.17 on 2026-09-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rentalapplication_landlord_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('CONTACT_FORM', 'Contact form'), ('PROPERTY_INQUIRY', 'Property inquiry'), ('AGENT_INQUIRY', 'Agent inquiry'), ('REFERRAL', 'Referral'), ('GOOGLE', 'Google'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('DIRECT', 'Direct'), ('CALLBACK', 'Callback request'), ('PHONE_AGENT', 'AI phone agent')], default='CONTACT_FORM', max_length=24),
        ),
    ]
