# Generated by Django 5.2.17 on 2026-09-24 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead_source_phone_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_consent_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_countersigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_countersigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_countersigned_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_signed_user_agent',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_signer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_terms_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='landlord_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='owner address for notices'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='landlord_company',
            field=models.CharField(blank=True, default='', help_text='The company or individual that owns the home. Required before a lease is sent.', max_length=200, verbose_name='owner (landlord)'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='landlord_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='owner email'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='landlord_name',
            field=models.CharField(blank=True, default='', help_text='Optional: the person who signs for the owning company.', max_length=200, verbose_name='owner contact person'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='landlord_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='owner phone'),
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('INCOME_PROOF', 'Proof of income'), ('ID', 'Photo ID'), ('VOUCHER_LETTER', 'Housing voucher letter'), ('GUARANTOR_INFO', 'Guarantor details or documents'), ('OTHER', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True, default='', help_text='Shown to the applicant. Say exactly what you need.')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SUBMITTED', 'Submitted - waiting for review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Needs another upload')], db_index=True, default='REQUESTED', max_length=12)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='', help_text='Shown to the applicant when you ask again.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='crm.rentalapplication')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('INCOME_PROOF', 'Proof of income'), ('ID', 'Photo ID'), ('VOUCHER_LETTER', 'Housing voucher letter'), ('GUARANTOR_INFO', 'Guarantor details or documents'), ('OTHER', 'Other')], max_length=20)),
                ('stored_name', models.CharField(max_length=200)),
                ('original_name', models.CharField(blank=True, default='', max_length=200)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.rentalapplication')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.documentrequest')),
            ],
            options={
                'db_table': 'application_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('monthly_income_cents', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='crm.rentalapplication')),
            ],
            options={
                'db_table': 'application_guarantors',
            },
        ),
        migrations.AddConstraint(
            model_name='documentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('review_note', ''), _negated=True), _connector='OR'), name='rejected_document_request_has_note'),
        ),
        migrations.AddConstraint(
            model_name='guarantor',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_income_cents__isnull', True), ('monthly_income_cents__gte', 0), _connector='OR'), name='guarantor_income_not_negative'),
        ),
    ]
