# Generated by Django 5.2.17 on 2026-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_scrub_draft_pii'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='deposit_held_at',
            field=models.CharField(blank=True, default='', help_text='Bank name and address, and whether the account earns interest. Required in FL, GA, NC, TN and WA.', max_length=300, verbose_name='where the deposit is held'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='flood_history',
            field=models.TextField(blank=True, default='', help_text="Flooding of the home in the last five years, or 'None known'. Required in TX and GA.", verbose_name='flooding the owner knows of'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='flood_zone_known',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', help_text='Is the owner aware the home is in a 100-year floodplain / special flood hazard area? Required in TX and CA.', max_length=3, verbose_name='owner knows the home is in a flood zone'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='lead_hazards_known',
            field=models.TextField(blank=True, default='', help_text="Known lead-based paint or hazards and any reports, or 'None known'. Required for homes built before 1978 or of unknown age.", verbose_name='known lead paint hazards'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='other_hazards_known',
            field=models.TextField(blank=True, default='', help_text="Radon or mold test results, outstanding inspection or condemnation orders - or 'None known'. Required in CA, IL and MN.", verbose_name='other things the owner must disclose'),
        ),
    ]
