# Generated by Django 5.1.15 on 2026-08-17 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=300)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('max_scroll_depth', models.PositiveSmallIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'page_visits',
            },
        ),
        migrations.CreateModel(
            name='RawTelemetryEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'raw_telemetry_events',
                'indexes': [models.Index(fields=['processed', 'received_at'], name='raw_telemet_process_6ac218_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_sessions_count', models.PositiveIntegerField(default=0)),
                ('total_dwell_seconds', models.PositiveIntegerField(default=0)),
                ('primary_device', models.CharField(blank=True, default='', max_length=40)),
                ('primary_city', models.CharField(blank=True, default='', max_length=100)),
                ('is_lead', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visitors',
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('browser', models.CharField(blank=True, default='', max_length=60)),
                ('os', models.CharField(blank=True, default='', max_length=60)),
                ('device_type', models.CharField(blank=True, default='', max_length=40)),
                ('landing_page', models.CharField(blank=True, default='', max_length=300)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('properties_viewed_count', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_dwell_seconds', models.PositiveIntegerField(default=0)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.visitor')),
            ],
            options={
                'db_table': 'visitor_sessions',
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.pagevisit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitorsession')),
            ],
            options={
                'db_table': 'telemetry_events',
            },
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='analytics.visitorsession'),
        ),
    ]
